// Generated by CoffeeScript 1.4.0
(function() {
  var should;

  should = require("should");

  describe('Array', function() {
    return describe('#indexOf()', function() {
      return it('should return -1 when the value is not present', function() {
        return should.equal(-1, [1, 2, 3].indexOf(5));
      });
    });
  });

}).call(this);
