// Generated by CoffeeScript 1.4.0

/*jshint node: true
*/


(function() {
  "use strict";

  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: "<json:package.json>",
      dirs: {
        jsSrc: './public/js',
        dest: '../dist/'
      },
      meta: {
        name: "<%= pkg.name %>",
        banner: "/*! <%= meta.name %> - v<%= pkg.version %> - <%= grunt.template.today(\"m/d/yyyy\") %>\n" + "* <%= pkg.homepage %>\n" + "* Copyright (c) <%= grunt.template.today(\"yyyy\") %> <%= pkg.author.name %>;*/"
      },
      lint: {
        files: ["*.js", "config/*.js", "routes/*.js", "mocha/test/**/*.js", "public/js/*.js", "public/js/views/*.js", "public/js/models/*.js"]
      },
      concat: {
        dist: {
          src: ["<banner>", "public/js/*.js"],
          dest: '<%= dirs.dest %>/public/js/main.js'
        }
      },
      copy: {
        dist: {
          files: {
            "<%= dirs.dest %>/": "./*",
            "<%= dirs.dest %>/config/": "./config/**",
            "<%= dirs.dest %>/routes/": "./routes/**",
            "<%= dirs.dest %>/views/": "./views/**",
            "<%= dirs.dest %>/public/css/": "./public/css/**",
            "<%= dirs.dest %>/public/images/": "./public/images/**"
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib');
    grunt.registerTask("default", "lint");
    return grunt.registerTask("build", "lint copy");
  };

}).call(this);
